baseURL = 'https://keminghe.github.io/contrib-dev-website'
languageCode = 'en-us'
title = 'DEV - Software Engineering Club at OSU'
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[markup.goldmark.renderer]
unsafe= true