baseURL = 'https://contrib-dev-website.hes-solutions.tech'
languageCode = 'en-us'
title = 'DEV - Software Engineering Club at OSU'
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[markup.goldmark.renderer]
unsafe= true